### ISSUE TITLE
features location

### ISSUE THREAD

**Issue by RytisJ** [prashant-ramcharan/courgette-jvm-example#2]
Hi,

Like your work, how comes if you set features location as "classpath:features" causes parallelism to be repeated?

**Comment by prashant-ramcharan** [comment]
Hello, 

Good question. 

The reason is Courgette uses the provided feature path to build a new classpath for each individual scenario / feature.

So when a classpath is provided in the Courgette runner (_features location_), it will conflict with how Courgette rebuilds the classpath. This causes each scenario / feature to be executed more than once by the Cucumber CLI.
